// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO2JjiFJACm-zjFw9feLVmqW8jiu4DmU8',
    appId: '1:92444002158:web:37aaa506a77e32d2ff637f',
    messagingSenderId: '92444002158',
    projectId: 'padelbud-99086',
    authDomain: 'padelbud-99086.firebaseapp.com',
    storageBucket: 'padelbud-99086.firebasestorage.app',
    measurementId: 'G-GGPRCSE7LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1jXVtTNw0mWVpPLPI7Zct7Ua-1Js6mg',
    appId: '1:92444002158:android:0ef07e970f865de6ff637f',
    messagingSenderId: '92444002158',
    projectId: 'padelbud-99086',
    storageBucket: 'padelbud-99086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTeuq-ibNZ8BBCeCurmJSU7jSx7ak1hA',
    appId: '1:92444002158:ios:06493a9600ba60eaff637f',
    messagingSenderId: '92444002158',
    projectId: 'padelbud-99086',
    storageBucket: 'padelbud-99086.firebasestorage.app',
    iosBundleId: 'com.buddies.padelBud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmTeuq-ibNZ8BBCeCurmJSU7jSx7ak1hA',
    appId: '1:92444002158:ios:06493a9600ba60eaff637f',
    messagingSenderId: '92444002158',
    projectId: 'padelbud-99086',
    storageBucket: 'padelbud-99086.firebasestorage.app',
    iosBundleId: 'com.buddies.padelBud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO2JjiFJACm-zjFw9feLVmqW8jiu4DmU8',
    appId: '1:92444002158:web:a35479f0ce687863ff637f',
    messagingSenderId: '92444002158',
    projectId: 'padelbud-99086',
    authDomain: 'padelbud-99086.firebaseapp.com',
    storageBucket: 'padelbud-99086.firebasestorage.app',
    measurementId: 'G-EQLXT4N0V9',
  );
}
